# Generated by Django 6.0.6 on 2026-07-01 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_message_status'),
    ]

    operations = [
    ]
