# Generated by Django 6.0.6 on 2026-07-01 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0004_drop_is_read'),
    ]

    operations = [
    ]
