# Generated by Django 6.0.6 on 2026-07-01 13:37
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0005_drop_is_read'),
    ]

    operations = [
        migrations.RunSQL(
            sql="SELECT 1;",
            reverse_sql="ALTER TABLE messaging_message ADD COLUMN is_read boolean NOT NULL DEFAULT false;",
        ),
    ]