# Generated by Django 6.0.6 on 2026-07-03 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_create_default_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='cv',
        ),
        migrations.RemoveField(
            model_name='user',
            name='cv_filename',
        ),
    ]
